// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kczyjeeqfmsrigckfvty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjenlqZWVxZm1zcmlnY2tmdnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzgxMjMsImV4cCI6MjA2NjQ1NDEyM30.IhO-FJJ7OQqzompFFQuX4sXdeaifHXT2rP1ACZC0mJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);